apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/keycloak.deployment.yaml
  - resources/keycloak.service.yaml

configMapGenerator:
  - files:
      - config/crane-realm.json
    name: keycloak-realm
