apiVersion: v1
kind: Pod
metadata:
  name: crane
  labels:
    ci: crane-build
spec:
  containers:
    - name: builder
      image: registry.openanalytics.eu/proxy/library/maven:3-openjdk-17
      command:
        - cat
      tty: true
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources:
        requests:
          memory: "2Gi"
          cpu: "1.0"
        limits:
          memory: "4Gi"
          cpu: "1.5"
    - name: docker
      image: docker:dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      resources:
        requests:
          memory: "2Gi"
          cpu: "1.0"
        limits:
          memory: "4Gi"
          cpu: "1.5"
