apiVersion: v1
kind: Pod
metadata:
  name: crane
  labels:
    ci: crane-build
spec:
  containers:
   - name: builder
     image: registry.openanalytics.eu/proxy/library/maven:3-openjdk-11
     command:
     - cat
     tty: true
     resources:
       requests:
         memory: "2Gi"
         cpu: "1.0"
       limits:
         memory: "4Gi"
         cpu: "1.5"
