app:
  storage-location: /mnt/crane/
  openid-issuer-uri: "${OAUTH2_ISSUER_URI}"
  repositories:
    - name: project1
      public: true
    - name: project2
      public: false

spring:
  security:
    oauth2:
      client:
        registration:
          crane:
            client-secret: "${OAUTH2_CLIENT_SECRET}"
            client-id: "${OAUTH2_CLIENT_ID}"
            scope: openid
        provider:
          crane:
            issuer-uri: "${OAUTH2_ISSUER_URI}"
