apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/crane.deployment.yaml
  - resources/crane.service.yaml
  - resources/crane.sa.yaml

configMapGenerator:
  - files:
      - config/application.yml
    name: crane
