apiVersion: v1
kind: Service
metadata:
  name: crane
  labels:
    app: crane
spec:
  ports:
    - name: http-crane
      protocol: TCP
      port: 8080
      targetPort: http-crane
  selector:
    app: crane
