apiVersion: apps/v1
kind: Deployment
metadata:
  name: crane
spec:
  selector:
    matchLabels:
      app: crane
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crane
    spec:
      serviceAccountName: crane-sa
      terminationGracePeriodSeconds: 80
      containers:
        - name: crane
          ports:
            - containerPort: 8080
              name: http-crane
          image: openanalytics/crane:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/crane/application.yml
              subPath: application.yml
              name: crane-config
            - mountPath: /mnt/crane
              name: data
          envFrom:
            - secretRef:
                name: crane-client-creds
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 9090
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 9090
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 3
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /actuator/health/liveness
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
      volumes:
        - name: crane-config
          configMap:
            name: crane
        - name: data
          emptyDir: {}
