apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.0
          args: [ "start-dev", "--import-realm" ]
          env:
            - name: KC_PROXY
              value: "edge"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: keycloak-volume
              mountPath: /opt/keycloak/data/import
          readinessProbe:
            httpGet:
              path: /auth/realms/crane
              port: 8080
      volumes:
        - name: keycloak-volume
          configMap:
            name: keycloak-realm
